# Generated by Django 3.1.3 on 2020-11-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20201110_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
